compatibility_date = "2024-11-01"

[vars]
COOKIE_NAME = "token"

[[r2_buckets]]
binding = "R2_DOCUMENTS"
bucket_name = "documents"   # <-- change this to your actual R2 bucket name

[[d1_databases]]
binding = "DB"
database_name = "ai_accountant"  # <-- change to your actual D1 db name
database_id = "ai_accountant"    # <-- change to your actual D1 db id
migrations_dir = "migrations"
